-- allowPublicKeyRetrieval=true jdbc || GET_SOURCE_PUBLIC_KEY = 1;
STOP REPLICA;
CHANGE REPLICATION SOURCE TO
    SOURCE_HOST='mysql-master',
    SOURCE_PORT=3306,
    SOURCE_USER='repl',
    SOURCE_PASSWORD='passwd',
    SOURCE_AUTO_POSITION=1,
    GET_SOURCE_PUBLIC_KEY = 1;


START REPLICA;

SHOW REPLICA STATUS;